export { default as Terminal } from './Terminal.vue'
export type { TerminalProps } from './Terminal.vue'
export { default as AnimatedSpan } from './AnimatedSpan.vue'
export type { AnimatedSpanProps } from './AnimatedSpan.vue'
export { default as TerminalTypingAnimation } from './TerminalTypingAnimation.vue'
export type { TerminalTypingAnimationProps } from './TerminalTypingAnimation.vue'
