export { default as Confetti } from './Confetti.vue'
export type { ConfettiProps } from './Confetti.vue'
export { default as ConfettiButton } from './ConfettiButton.vue'
export type { ConfettiButtonProps } from './ConfettiButton.vue'
export { useConfetti } from './context'
export type { ConfettiRef } from './context'
